--
--  List of world's countries containing the official short names in English as given by ISO 3166-1,
--  the ISO 3166-1-alpha-2 code provided by the International Organization for Standardization
--  (https://www.iso.org/obp/ui/#search)
--  and the ISO alpha-3 code provided by the United Nations Statistics Division
--  (http://unstats.un.org/unsd/methods/m49/m49alpha.htm)
--
--  https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#AL
--

IF NOT EXISTS (SELECT 1 FROM [dbo].[Countries])
BEGIN
INSERT INTO Countries (Code, Name, OfficialName) VALUES
	('AF', 'Afghanistan', 'Afghanistan'),
	('AX', 'Aland Islands', 'Aland Islands'),
	('AL', 'Albania', 'Albania'),
	('DZ', 'Algeria', 'Algeria'),
	('AS', 'American Samoa', 'American Samoa'),
	('AD', 'Andorra', 'Andorra'),
	('AO', 'Angola', 'Angola'),
	('AI', 'Anguilla', 'Anguilla'),
	('AQ', 'Antarctica', 'Antarctica'),
	('AG', 'Antigua and Barbuda', 'Antigua and Barbuda'),
	('AR', 'Argentina', 'Argentina'),
	('AM', 'Armenia', 'Armenia'),
	('AW', 'Aruba', 'Aruba'),
	('AU', 'Australia', 'Australia'),
	('AT', 'Austria', 'Austria'),
	('AZ', 'Azerbaijan', 'Azerbaijan'),
	('BS', 'Bahamas', 'Bahamas'),
	('BH', 'Bahrain', 'Bahrain'),
	('BD', 'Bangladesh', 'Bangladesh'),
	('BB', 'Barbados', 'Barbados'),
	('BY', 'Belarus', 'Belarus'),
	('BE', 'Belgium', 'Belgium'),
	('BZ', 'Belize', 'Belize'),
	('BJ', 'Benin', 'Benin'),
	('BM', 'Bermuda', 'Bermuda'),
	('BT', 'Bhutan', 'Bhutan'),
	('BO', 'Bolivia', 'Plurinational State of Bolivia'),
	('BQ', 'Bonaire', 'Sint Eustatius and Saba Bonaire'),
	('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
	('BW', 'Botswana', 'Botswana'),
	('BV', 'Bouvet Island', 'Bouvet Island'),
	('BR', 'Brazil', 'Brazil'),
	('IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory'),
	('BN', 'Brunei Darussalam', 'Brunei Darussalam'),
	('BG', 'Bulgaria', 'Bulgaria'),
	('BF', 'Burkina Faso', 'Burkina Faso'),
	('BI', 'Burundi', 'Burundi'),
	('KH', 'Cambodia', 'Cambodia'),
	('CM', 'Cameroon', 'Cameroon'),
	('CA', 'Canada', 'Canada'),
	('CV', 'Cape Verde', 'Cape Verde'),
	('KY', 'Cayman Islands', 'Cayman Islands'),
	('CF', 'Central African Republic', 'Central African Republic'),
	('TD', 'Chad', 'Chad'),
	('CL', 'Chile', 'Chile'),
	('CN', 'China', 'China'),
	('CX', 'Christmas Island', 'Christmas Island'),
	('CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'),
	('CO', 'Colombia', 'Colombia'),
	('KM', 'Comoros', 'Comoros'),
	('CG', 'Congo', 'Congo'),
	('CD', 'Zaire', 'The Democratic Republic of the Congo'),
	('CK', 'Cook Islands', 'Cook Islands'),
	('CR', 'Costa Rica', 'Costa Rica'),
	('CI', 'Cote d''Ivoire', 'Cote d''Ivoire'),
	('HR', 'Croatia', 'Croatia'),
	('CU', 'Cuba', 'Cuba'),
	('CW', 'Curacao', 'Curacao'),
	('CY', 'Cyprus', 'Cyprus'),
	('CZ', 'Czech Republic', 'Czech Republic'),
	('DK', 'Denmark', 'Denmark'),
	('DJ', 'Djibouti', 'Djibouti'),
	('DM', 'Dominica', 'Dominica'),
	('DO', 'Dominican Republic', 'Dominican Republic'),
	('EC', 'Ecuador', 'Ecuador'),
	('EG', 'Egypt', 'Egypt'),
	('SV', 'El Salvador', 'El Salvador'),
	('GQ', 'Equatorial Guinea', 'Equatorial Guinea'),
	('ER', 'Eritrea', 'Eritrea'),
	('EE', 'Estonia', 'Estonia'),
	('ET', 'Ethiopia', 'Ethiopia'),
	('FK', 'Falkland Islands (Malvinas)', 'Falkland Islands'),
	('FO', 'Faroe Islands', 'Faroe Islands'),
	('FJ', 'Fiji', 'Fiji'),
	('FI', 'Finland', 'Finland'),
	('FR', 'France', 'France'),
	('GF', 'French Guiana', 'Guiana'),
	('PF', 'French Polynesia', 'French Polynesia'),
	('TF', 'French Southern Territories', 'French Southern and Antarctic Lands'),
	('GA', 'Gabon', 'Gabon'),
	('GM', 'Gambia', 'Gambia'),
	('GE', 'Georgia', 'Georgia'),
	('DE', 'Germany', 'Germany'),
	('GH', 'Ghana', 'Ghana'),
	('GI', 'Gibraltar', 'Gibraltar'),
	('GR', 'Greece', 'Greece'),
	('GL', 'Greenland', 'Greenland'),
	('GD', 'Grenada', 'Grenada'),
	('GP', 'Guadeloupe', 'Guadeloupe'),
	('GU', 'Guam', 'Guam'),
	('GT', 'Guatemala', 'Guatemala'),
	('GG', 'Guernsey', 'Guernsey'),
	('GN', 'Guinea', 'Guinea'),
	('GW', 'Guinea-Bissau', 'Guinea-Bissau'),
	('GY', 'Guyana', 'Guyana'),
	('HT', 'Haiti', 'Haiti'),
	('HM', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'),
	('VA', 'Holy See (Vatican City State)', 'Holy See (Vatican City State)'),
	('HN', 'Honduras', 'Honduras'),
	('HK', 'Hong Kong', 'Hong Kong'),
	('HU', 'Hungary', 'Hungary'),
	('IS', 'Iceland', 'Iceland'),
	('IN', 'India', 'India'),
	('ID', 'Indonesia', 'Indonesia'),
	('IR', 'Iran', 'Islamic Republic of Iran'),
	('IQ', 'Iraq', 'Iraq'),
	('IE', 'Ireland', 'Ireland'),
	('IM', 'Isle of Man', 'Isle of Man'),
	('IL', 'Israel', 'Israel'),
	('IT', 'Italy', 'Italy'),
	('JM', 'Jamaica', 'Jamaica'),
	('JP', 'Japan', 'Japan'),
	('JE', 'Jersey', 'Jersey'),
	('JO', 'Jordan', 'Jordan'),
	('KZ', 'Kazakhstan', 'Kazakhstan'),
	('KE', 'Kenya', 'Kenya'),
	('KI', 'Kiribati', 'Kiribati'),
	('KP', 'North Korea', 'Democratic People''s Republic of Korea'),
	('KR', 'South Korea', 'Republic of Korea'),
	('KW', 'Kuwait', 'Kuwait'),
	('KG', 'Kyrgyzstan', 'Kyrgyzstan'),
	('LA', 'Lao People''s Democratic Republic', 'Lao People''s Democratic Republic'),
	('LV', 'Latvia', 'Latvia'),
	('LB', 'Lebanon', 'Lebanon'),
	('LS', 'Lesotho', 'Lesotho'),
	('LR', 'Liberia', 'Liberia'),
	('LY', 'Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya'),
	('LI', 'Liechtenstein', 'Liechtenstein'),
	('LT', 'Lithuania', 'Lithuania'),
	('LU', 'Luxembourg', 'Luxembourg'),
	('MO', 'Macao', 'Macao'),
	('MK', 'Macedonia', 'The former Yugoslav Republic of Macedonia'),
	('MG', 'Madagascar', 'Madagascar'),
	('MW', 'Malawi', 'Malawi'),
	('MY', 'Malaysia', 'Malaysia'),
	('MV', 'Maldives', 'Maldives'),
	('ML', 'Mali', 'Mali'),
	('MT', 'Malta', 'Malta'),
	('MH', 'Marshall Islands', 'Marshall Islands'),
	('MQ', 'Martinique', 'Martinique'),
	('MR', 'Mauritania', 'Mauritania'),
	('MU', 'Mauritius', 'Mauritius'),
	('YT', 'Mayotte', 'Mayotte'),
	('MX', 'Mexico', 'Mexico'),
	('FM', 'Micronesia', 'Federated States of Micronesia'),
	('MD', 'Moldova', 'Republic of Moldova'),
	('MC', 'Monaco', 'Monaco'),
	('MN', 'Mongolia', 'Mongolia'),
	('ME', 'Montenegro', 'Montenegro'),
	('MS', 'Montserrat', 'Montserrat'),
	('MA', 'Morocco', 'Morocco'),
	('MZ', 'Mozambique', 'Mozambique'),
	('MM', 'Myanmar', 'Myanmar'),
	('NA', 'Namibia', 'Namibia'),
	('NR', 'Nauru', 'Nauru'),
	('NP', 'Nepal', 'Nepal'),
	('NL', 'Netherlands', 'Netherlands'),
	('NC', 'New Caledonia', 'New Caledonia'),
	('NZ', 'New Zealand', 'New Zealand'),
	('NI', 'Nicaragua', 'Nicaragua'),
	('NE', 'Niger', 'Niger'),
	('NG', 'Nigeria', 'Nigeria'),
	('NU', 'Niue', 'Niue'),
	('NF', 'Norfolk Island', 'Norfolk Island'),
	('MP', 'Northern Mariana Islands', 'Northern Mariana Islands'),
	('NO', 'Norway', 'Norway'),
	('OM', 'Oman', 'Oman'),
	('PK', 'Pakistan', 'Pakistan'),
	('PW', 'Palau', 'Palau'),
	('PS', 'Palestinian Territory', 'Occupied Palestinian Territory'),
	('PA', 'Panama', 'Panama'),
	('PG', 'Papua New Guinea', 'Papua New Guinea'),
	('PY', 'Paraguay', 'Paraguay'),
	('PE', 'Peru', 'Peru'),
	('PH', 'Philippines', 'Philippines'),
	('PN', 'Pitcairn', 'Pitcairn'),
	('PL', 'Poland', 'Poland'),
	('PT', 'Portugal', 'Portugal'),
	('PR', 'Puerto Rico', 'Puerto Rico'),
	('QA', 'Qatar', 'Qatar'),
	('RE', 'Reunion', 'Reunion'),
	('RO', 'Romania', 'Romania'),
	('RU', 'Russia', 'Russian Federation'),
	('RW', 'Rwanda', 'Rwanda'),
	('BL', 'Saint Barthelemy', 'Saint Barthelemy'),
	('SH', 'Saint Helena', 'Ascension and Tristan Da Cunha Saint Helena'),
	('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
	('LC', 'Saint Lucia', 'Saint Lucia'),
	('MF', 'Saint Martin (French Part)', 'Saint Martin (French Part)'),
	('PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'),
	('VC', 'Saint Vincent and The Grenadines', 'Saint Vincent and The Grenadines'),
	('WS', 'Samoa', 'Samoa'),
	('SM', 'San Marino', 'San Marino'),
	('ST', 'Sao Tome and Principe', 'Sao Tome and Principe'),
	('SA', 'Saudi Arabia', 'Saudi Arabia'),
	('SN', 'Senegal', 'Senegal'),
	('RS', 'Serbia', 'Serbia'),
	('SC', 'Seychelles', 'Seychelles'),
	('SL', 'Sierra Leone', 'Sierra Leone'),
	('SG', 'Singapore', 'Singapore'),
	('SX', 'Sint Maarten (Dutch Part)', 'Sint Maarten (Dutch Part)'),
	('SK', 'Slovakia', 'Slovakia'),
	('SI', 'Slovenia', 'Slovenia'),
	('SB', 'Solomon Islands', 'Solomon Islands'),
	('SO', 'Somalia', 'Somalia'),
	('ZA', 'South Africa', 'South Africa'),
	('GS', 'South Georgia and The South Sandwich Islands', 'South Georgia and The South Sandwich Islands'),
	('SS', 'South Sudan', 'South Sudan'),
	('ES', 'Spain', 'Spain'),
	('LK', 'Sri Lanka', 'Sri Lanka'),
	('SD', 'Sudan', 'Sudan'),
	('SR', 'Suriname', 'Suriname'),
	('SJ', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
	('SZ', 'Swaziland', 'Swaziland'),
	('SE', 'Sweden', 'Sweden'),
	('CH', 'Switzerland', 'Switzerland'),
	('SY', 'Syrian Arab Republic', 'Syrian Arab Republic'),
	('TW', 'Taiwan', 'Province of China Taiwan'),
	('TJ', 'Tajikistan', 'Tajikistan'),
	('TZ', 'Tanzania', 'United Republic of Tanzania'),
	('TH', 'Thailand', 'Thailand'),
	('TL', 'Timor-Leste', 'Timor-Leste'),
	('TG', 'Togo', 'Togo'),
	('TK', 'Tokelau', 'Tokelau'),
	('TO', 'Tonga', 'Tonga'),
	('TT', 'Trinidad and Tobago', 'Trinidad and Tobago'),
	('TN', 'Tunisia', 'Tunisia'),
	('TR', 'Turkey', 'Turkey'),
	('TM', 'Turkmenistan', 'Turkmenistan'),
	('TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands'),
	('TV', 'Tuvalu', 'Tuvalu'),
	('UG', 'Uganda', 'Uganda'),
	('UA', 'Ukraine', 'Ukraine'),
	('AE', 'United Arab Emirates', 'United Arab Emirates'),
	('GB', 'UK', 'United Kingdom'),
	('US', 'USA', 'United States'),
	('UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands'),
	('UY', 'Uruguay', 'Uruguay'),
	('UZ', 'Uzbekistan', 'Uzbekistan'),
	('VU', 'Vanuatu', 'Vanuatu'),
	('VE', 'Venezuela', 'Bolivarian Republic of Venezuela'),
	('VN', 'Viet Nam', 'Viet Nam'),
	('VG', 'British Virgin Islands', 'Virgin Islands'),
	('VI', 'U.S. Virgin Islands', 'Virgin Islands of the United States'),
	('WF', 'Wallis and Futuna', 'Wallis and Futuna'),
	('EH', 'Western Sahara', 'Western Sahara'),
	('YE', 'Yemen', 'Yemen'),
	('ZM', 'Zambia', 'Zambia'),
	('ZW', 'Zimbabwe', 'Zimbabwe'),
	('DE', 'West Germany', 'West Germany'),
    ('DD', 'East Germany', 'German Democratic Republic'),
    ('SU', 'Soviet Union', 'Union of Soviet Socialist Republics'),
    ('YU', 'Yugoslavia', 'Yugoslavia')
END
