IF NOT EXISTS (SELECT 1 FROM [dbo].[Languages])
BEGIN
INSERT INTO Languages (Name) VALUES
    ('Aboriginal'),
    ('Afrikaans'),
    ('Albanian'),
    ('American Sign Language'),
    ('Apache languages'),
    ('Arabic'),
    ('Armenian'),
    ('Berber languages'),
    ('British Sign Language'),
    ('Bulgarian'),
    ('Burmese'),
    ('Cantonese'),
    ('Catalan'),
    ('Central Khmer'),
    ('Chinese'),
    ('Corsican'),
    ('Cree'),
    ('Croatian'),
    ('Czech'),
    ('Danish'),
    ('Dari'),
    ('Dutch'),
    ('Egyptian (Ancient)'),
    ('English'),
    ('English SDH'),
    ('Esperanto'),
    ('Estonian'),
    ('Filipino'),
    ('Finnish'),
    ('French'),
    ('French SDH'),
    ('Gaelic'),
    ('German'),
    ('German SDH'),
    ('Greek'),
    ('Greenlandic'),
    ('Guarani'),
    ('Hawaiian'),
    ('Hebrew'),
    ('Hindi'),
    ('Hmong'),
    ('Hungarian'),
    ('Icelandic'),
    ('Indonesian'),
    ('Irish Gaelic'),
    ('Italian'),
    ('Italian SDH'),
    ('Japanese'),
    ('Japanese Sign Language'),
    ('Klingon'),
    ('Korean'),
    ('Latin'),
    ('Latvian'),
    ('Lingala'),
    ('Lithuanian'),
    ('Mandarin'),
    ('Maori'),
    ('Mende'),
    ('Mohawk'),
    ('Music'),
    ('Navajo'),
    ('Nepali'),
    ('None'),
    ('Norwegian'),
    ('Old English'),
    ('Pawnee'),
    ('Persian'),
    ('Polish'),
    ('Portuguese'),
    ('Quenya'),
    ('Romanian'),
    ('Romany'),
    ('Russian'),
    ('Serbian'),
    ('Sicilian'),
    ('Sindarin'),
    ('Sinhala'),
    ('Sioux'),
    ('Slovak'),
    ('Slovenian'),
    ('Somali'),
    ('Spanish'),
    ('Swahili'),
    ('Swedish'),
    ('Swiss German'),
    ('Thai'),
    ('Turkish'),
    ('Ukrainian'),
    ('Ungwatsi'),
    ('Urdu'),
    ('Vietnamese'),
    ('Welsh'),
    ('Wolof'),
    ('Xhosa'),
    ('Yiddish'),
    ('Zulu')
END
